[package]
name = "typescript-wasm-bindgen"
version = "0.1.0"
authors = ["Inseok Lee <dlunch@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true
doctest = false

[dependencies]
syn = { version = "^1.0" }
quote = { version = "^1.0" }
proc-macro2 = { version = "^1.0" }
swc_common = { version = "^0.10" }
swc_ecma_parser = { version = "^0.44" }
swc_ecma_ast = { version = "^0.36" }

[dev-dependencies]
wasm-bindgen = { version = "^0.2" }
trybuild = { version = "^1.0" }